name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build release APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
        
    - name: Get version name
      id: version
      run: |
        VERSION=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/release/*.apk
        name: Release ${{ steps.version.outputs.version }}
        body: |
          ## Changes in this Release
          - Automated build via GitHub Actions
          - Modern Android build tools
          
          ## Installation
          1. Download the APK
          2. Install via your preferred method
          3. Activate in Xposed/LSPosed
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
